os: linux
dist: focal

env:
  - DOCKER_COMPOSE_VERSION=1.29.0
addons:
  chrome: stable

language: node_js
cache:
  yarn: false
node_js:
  - "10"
  - "12"
  - "14"
  - "16"

services:
  - docker

before_install:
  - docker --version
  - docker-compose --version
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - docker-compose --version
  - make up

install:
  - yarn install

before_script:
  - yarn lint

script: 
  - yarn test

after_success:
  - yarn pack
