os: linux
dist: focal

env:
  - DOCKER_COMPOSE_VERSION=1.4.2
addons:
  chrome: stable

language: node_js
cache:
  yarn: false
node_js:
  - "10"
  - "12"
  - "14"
  - "16"

services:
  - docker

before_install:
  - docker --version
  - docker-compose --version
  - make up

install:
  - yarn install

before_script:
  - yarn lint

script: 
  - yarn test

after_success:
  - 'cat ./coverage/lcov.info | ./node_modules/.bin/coveralls'

