sudo: required
dist: focal
language: node_js
env:
  - DOCKER_COMPOSE_VERSION=1.29.0
cache:
  yarn: false
addons:
  chrome: stable

node_js:
  - "10"
  - "12"
  - "14"
  - "16"

services:
  - docker

after_success:
  - 'cat ./coverage/lcov.info | ./node_modules/.bin/coveralls'

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - make up

install:
  - yarn install

before_script:
  - yarn lint

script: 
  - yarn test
