sudo: required
dist: trusty
language: node_js
addons:
  chrome: stable
node_js:
  - "6"
  - "8"
  - "10"
  - "11"

services:
  - docker

after_success:
  - 'cat ./coverage/lcov.info | ./node_modules/.bin/coveralls'

install:
  - npm install

before_install:
  - ./scripts/start-server.sh

before_script:
  - make lint

script: 
  - ./run-tests.sh
