sudo: required
dist: focal
language: node_js
cache:
  yarn: false
addons:
  chrome: stable

node_js:
  - "10"
  - "12"
  - "14"
  - "16"

services:
  - docker

after_success:
  - 'cat ./coverage/lcov.info | ./node_modules/.bin/coveralls'

before_install:
  - make up

install:
  - yarn install

before_script:
  - yarn lint

script: 
  - yarn test
